spring:
    profiles:
        active:
        - dev
        
spring:
    profiles: dev
    application: 
        name: microsoftservice-config-llc-dev

spring:
    profiles: test
    application: 
        name: microsoftservice-config-llc-test